development:
  adapter: postgresql
  encoding: unicode
  database: nrs_invoices_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: nrs_invoices_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: nrs_invoices_production
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>